mixed-port: 7890
socks-port: 7891
bind-address: "*"
allow-lan: true
external-controller: 0.0.0.0:9090

proxies:
  - name: "JP-KDDI-1"
    type: hysteria2
    server: 35.78.131.96
    port: 31342
    password: vHtRqxtpLfBU9wv2kHxDkoCT8
    sni: bing.com
    skip-cert-verify: true

  - name: "JP-KDDI-2"
    type: hysteria2
    server: 13.192.29.169
    port: 17411
    password: B0HsFhg0MKBCEuAVnIDytKyBoc
    sni: bing.com
    skip-cert-verify: true

  - name: "CA-Bell-1"
    type: hysteria2
    server: 15.156.107.6
    port: 26729
    password: 9sFNXMUatOwxc9R9i2nEMuWs8
    sni: bing.com
    skip-cert-verify: true

  - name: "CA-Bell-2"
    type: hysteria2
    server: 15.156.145.239
    port: 28626
    password: nO9e7M7mRm3YURx8a89tYLUhuws
    sni: bing.com
    skip-cert-verify: true

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - JP-KDDI-1
      - JP-KDDI-2
      - CA-Bell-1
      - CA-Bell-2

rules:
  - MATCH,Proxy
